# Generated by Django 2.2.16 on 2023-03-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
    ]
