# Generated by Django 2.2.16 on 2023-03-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_auto_20230308_1045'),
    ]

    operations = [
    ]
