# Generated by Django 2.2.16 on 2023-03-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_auto_20230326_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='units',
            new_name='measurement_unit',
        ),
    ]
