# Generated by Django 2.2.16 on 2023-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0005_auto_20230327_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, max_length=200, null=True, upload_to='images', verbose_name='Изображение рецепта'),
        ),
    ]
