# Generated by Django 2.2.16 on 2023-03-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0006_auto_20230327_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, max_length=2000000, null=True, upload_to='images', verbose_name='Изображение рецепта'),
        ),
    ]
