# Generated by Django 2.2.16 on 2023-03-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_auto_20230328_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='recipies/images', verbose_name='Изображение рецепта'),
        ),
    ]
