# Generated by Django 2.2.16 on 2023-03-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0011_auto_20230312_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipies.IngredientRecipe', to='recipies.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', through='recipies.TagRecipe', to='recipies.Tag'),
        ),
    ]
