# Generated by Django 2.2.16 on 2023-03-29 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0011_auto_20230329_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{1,2}){3}$', '^#(?:[0-9a-fA-F]{1,2}){3}$')], verbose_name='Цвет'),
        ),
    ]
