# Generated by Django 2.2.16 on 2023-03-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230308_1113'),
    ]

    operations = [
    ]
