# Generated by Django 2.2.16 on 2023-03-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230308_1245'),
    ]

    operations = [
    ]
