# Generated by Django 2.2.16 on 2023-03-12 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipies', '0008_auto_20230312_0835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritedRecipes',
            new_name='FavoriteRecipes',
        ),
    ]
