# Generated by Django 2.2.16 on 2023-03-19 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0013_auto_20230318_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
