name: Django-app workflow

on: [push]

jobs:
  preparing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          # обновление pip
          python -m pip install --upgrade pip 
          # установка flake8 и его плагинов
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          # установка зависимостей
          pip install -r backend/requirements.txt
  build_backend_and_push_to_docker_hub:
    name: Push Docker backend image to Docker Hub
    runs-on: ubuntu-latest
    needs: preparing
    if: contains('
      refs/heads/master
      refs/heads/main
      ', github.ref)
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: backend/
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
          file: backend/Dockerfile
  build_frontend_and_push_to_docker_hub:
    name: Push Docker frontend image to Docker Hub
    runs-on: ubuntu-latest
    needs: build_backend_and_push_to_docker_hub
    if: contains('
      refs/heads/master
      refs/heads/main
      ', github.ref)
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: frontend/
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          file: frontend/Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build_frontend_and_push_to_docker_hub
    if: contains('
      refs/heads/master
      refs/heads/main
      ', github.ref)
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }} # Если ваш ssh-ключ защищён фразой-паролем
          script: |
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker image prune -af
            sudo docker pull edmpeople/backend
            sudo docker pull edmpeople/frontend
            sudo docker-compose up -d
            sudo docker-compose exec -T backend python backend/manage.py makemigrations
            sudo docker-compose exec -T backend python backend/manage.py migrate
            sudo docker-compose exec -T backend python backend/manage.py collectstatic --no-input
